name: deploy react application
on: push
jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install all dependencies
        run: npm install
      - name: Lint the code
        run: npm run lint
      - name: Test the code
        run: npm test
      - name: Build the code
        run: npm run build
  deploy:
    needs: lint-test-build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: deploy the code
        run: echo "deployed"

    